#!/bin/bash


export OUR_OWN_IP=`sudo -u nobody curl -s ipinfo.io/ip`
readarray -t templine <<< $(ip -br addr | grep $OUR_OWN_IP)
temp=$(echo $templine[0] | awk '{print $1}')
export OUR_WAN_INTERFACE=$temp


#export OUR_OWN_IP=`sudo -u nobody curl -s ipinfo.io/ip`

#templine=$(ip -br addr | grep $OUR_OWN_IP)
echo "templine  " $templine[0]
echo "Our own IP " $OUR_OWN_IP
echo "Our Wan Interface " $OUR_WAN_INTERFACE
